name: Deploy Worker

on:
  push:
    paths:
      - 'workers/analyze-food/**' # Só roda se algo mudar nesta pasta
    branches:
      - main
  workflow_dispatch: # Permite rodar manualmente pelo GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Deploy com Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'workers/analyze-food'
          secrets: |
            GEMINI_API_KEY
          command: deploy
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
